
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Providers } from "../providers";
import Sidebar from "../components/sidebar/sideBar";
import "../../app/globals.css";
import HeaderAuth from "../components/header/headerAuth";
import FooterAuth from "../components/footer/footerAuth";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Metodo Ponte 100',
  description: 'Generated by RahamsisCG.',
};

// if (status === "loading") {
//     return <LoadingSpinner />;
//   }

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen overflow-x-hidden ${inter.className}`}>
        <Providers>
          <div className="flex flex-row w-full">
            <Sidebar />
            <div className="flex flex-col flex-1">
              <HeaderAuth />
              <main className="lg:pl-32 flex-1 overflow-auto">
                {children}
              </main>
              <FooterAuth/>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
