
// import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { metadata } from './metadata';

import HeaderLanding from "../components/header/headerLanding";
import Footer from "../components/footer/footerLanding";
import "../../app/globals.css";

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Metodo Ponte 100',
//   description: 'Generated by RahamsisCG.',
// };

// if (status === "loading") {
//     return <LoadingSpinner />;
//   }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
 const getImageUrl = () => {
    if (Array.isArray(metadata.openGraph?.images)) {
      return typeof metadata.openGraph.images[0] === 'object' && 'url' in metadata.openGraph.images[0]
        ? metadata.openGraph.images[0].url
        : "";
    }
    return "";
  };

  const getImageAlt = () => {
    if (Array.isArray(metadata.openGraph?.images)) {
      return typeof metadata.openGraph.images[0] === 'object' && 'alt' in metadata.openGraph.images[0]
        ? metadata.openGraph.images[0].alt
        : "";
    }
    return "";
  };

  return (
    <html lang="en">
      <head>
        <title>PONTE 100™ - Simulador de Exámenes</title>
        <meta name="description" content={metadata.description || ""} />
        <meta property="og:title" content={String(metadata.openGraph?.title) || ""} />
        <meta property="og:description" content={String(metadata.openGraph?.description) || ""} />
        <meta property="og:url" content={String(metadata.openGraph?.url) || ""} />
        <meta property="og:site_name" content={String(metadata.openGraph?.siteName) || ""} />
        <meta property="og:image" content={getImageUrl().toString()} />
        <meta property="og:image:alt" content={getImageAlt()} />
      </head>
      <body className={`flex min-h-screen ${inter.className}`}>
        {/* <Providers> */}
          <div className="flex flex-row w-full">
            <div className="flex flex-col flex-1">
              <HeaderLanding />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </div>
          </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
