
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Providers } from "../providers";
import HeaderLanding from "../components/header/headerLanding";
import Footer from "../components/footer/footerLanding";
import "../../app/globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Metodo Ponte 100',
  description: 'Generated by RahamsisCG.',
};

// if (status === "loading") {
//     return <LoadingSpinner />;
//   }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen ${inter.className}`}>
        {/* <Providers> */}
          <div className="flex flex-row w-full">
            <div className="flex flex-col flex-1">
              <HeaderLanding />
              <main className="flex-1">
                {children}
              </main>
              <Footer />
            </div>
          </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
